vim.keymap.set("i", "<C-BS>", "<C-w>")
vim.keymap.set("i", "<C-Del>", "<C-o>dw")
vim.keymap.set("i", "<C-q>", "<C-o>:qa<CR>")
vim.keymap.set("i", "<C-s>", "<C-o>:w<CR>")
vim.keymap.set("i", "<C-e>", "<C-o>:norm gcc<CR>", {remap = true})
vim.keymap.set("i", "<A-t>", "<Esc>:Neotree focus<CR>")
vim.keymap.set("n", "<A-t>", "<C-w> h i")
